### ISSUE TITLE
units: zusätzliche Einheit

### ISSUE THREAD

**Issue by Tessi87** [medizininformatik-initiative/Projectathon7#3]
Bei wird die Einheit statt mit ng/L mit ng/l angegeben. Dies müsste in der units-Funktion (Zeile 245) hinzugefügt werden.

**Comment by astruebi** [comment]
Zeile 260 kann man entnehmen, dass die im Code angegebenen Units Case-insensitiv geprüft werden (grepl mit ignore.case = TRUE). Alle angegebenen Einheiten werden in beliebiger Groß-Klein-Schreibung gefunden.

ACHTUNG: Bitte keine Iussues hier eintragen. Das Projekt steht jetzt unter https://github.com/medizininformatik-initiative/Projectathon7-VHF
