### ISSUE TITLE
Problems to download the docker image

### ISSUE THREAD

**Issue by Goldkugel** [medizininformatik-initiative/Projectathon7#4]
Dear Projectathon team,

we tried to run the selection and analysis scripts (https://github.com/medizininformatik-initiative/Projectathon7-VHF) in our production environment, but due to proxy restrictions, we have the situation that we cannot access the registry (registry.gitlab.com/smith-phep/dup).

Instead, we use an internal registry, which then forwards to registry.gitlab.com or communicates with it. With this method, we can successfully download the VHF image via the command line (see screenshot).

In the config.toml we changed the registry from "registry.gitlab.com/smith-phep/dup" to "gitlab.nexus/smith-phep/dup" (our local registry runs under gitlab.nexus). However, when we run the "dupctl retrieve --dup vhf" command, we get an error message that seems to be related to the docker image (see screenshot).

Could you help us with this?

Thank you and best regards,
AIIM Team of TUM Munich

![pastedImage(1)](https://user-images.githubusercontent.com/100677854/205937645-84965a54-686e-43ce-9866-922c00016455.png)

**Comment by knoppiks** [comment]
This seems to be related to your local container registry. Does it require authentication?
We removed the authentication parameter from the config Documentation when we decided to use a publicly available registry. But they are still there, see https://github.com/medizininformatik-initiative/dup-control/blob/main/cmd/root.go#L111

You can use `registryUser` and `registryPass` to make dupctl work with a basic auth protected registry.

**Comment by Goldkugel** [comment]
Hello knoppiks,

thank you very much, the problem has been solved with your hint!

Best 

AIIM Team of TUM Munich
